# azure-pipelines.yml
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Stage1
  displayName: 'Initial Stage'
  jobs:
  - job: HelloWorldJob
    steps:
    - task: PowerShell@2
      displayName: 'Hello World'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Hello, World from Azure DevOps Pipeline!"
          Write-Host "Current time is: $(Get-Date)"
          Write-Host "Running on branch: $(Build.SourceBranchName)"

    - task: PowerShell@2
      displayName: 'Show Environment Variables'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Pipeline ID: $(System.DefinitionId)"
          Write-Host "Build ID: $(Build.BuildId)"
          Write-Host "Agent Name: $(Agent.Name)"
          
          # Display custom variables if passed to the pipeline
          if ($env:ENVIRONMENT) {
            Write-Host "Custom variable - Environment: $env:ENVIRONMENT"
          }
          if ($env:DEPLOYTARGET) {
            Write-Host "Custom variable - Deploy Target: $env:DEPLOYTARGET"
          }

- stage: TestDeploy
  displayName: 'Stage Requiring Test Approval'
  dependsOn: Stage1
  jobs:
  - deployment: DeploymentJob
    displayName: 'Deployment with Approval'
    environment: 'Test'  # This creates the approval requirement
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Post-Approval Steps'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This step was executed after approval!"
                Write-Host "Approval time: $(Get-Date)"
                Write-Host "The approver granted permission to proceed."

- stage: StageDeploy
  displayName: 'Stage Requiring Prod Approval'
  dependsOn: Stage1
  jobs:
  - deployment: DeploymentJob
    displayName: 'Deployment with Approval'
    environment: 'Stage'  # This creates the approval requirement
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Post-Approval Steps'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This step was executed after approval!"
                Write-Host "Approval time: $(Get-Date)"
                Write-Host "The approver granted permission to proceed."

- stage: ProdDeploy
  displayName: 'Stage Requiring Prod Approval'
  dependsOn: StageDeploy
  jobs:
  - deployment: DeploymentJob
    displayName: 'Deployment with Approval'
    environment: 'Prod'  # This creates the approval requirement
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Post-Approval Steps'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This step was executed after approval!"
                Write-Host "Approval time: $(Get-Date)"
                Write-Host "The approver granted permission to proceed."